packages:
  - "."

allowBuilds:
  '@discordjs/opus': true
  esbuild: true

minimumReleaseAgeExclude:
  - vite@8.1.2
  - '@typescript/*'
  - typescript

overrides:
  '@discordjs/node-pre-gyp@0.4.5>tar': 7.5.16
  semver: 7.8.1
